---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  annotations:
        prometheus.io/scrape: 'true'
  labels:
    name: frontend
  namespace: sock-shop
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8079
    nodePort: 30001
  selector:
    name: frontend