apiVersion: v1
kind: Service
metadata:
  labels:
    app: movie
  name: movie
spec:
  type: NodePort
  ports:
  - name: "movie-service"
    port: 5000
    targetPort: 80
    nodePort: 31000
  selector:
    app: vote
  
