apiVersion: v1
kind: Service
metadata:
  labels:
    app: movies
  name: movies
spec:
  type: NodePort
  ports:
  - name: "movie-service"
    port: 5000
    targetPort: 8000
    nodePort: 31000
  selector:
    app: movies
  
